### ISSUE TITLE
Stim, Surface Code and Parity check matrix

### ISSUE THREAD

**Issue by yoyocni** [oscarhiggott/PyMatching#73]
Thank you for the great repo!
I can see many other are interested in surface code (from parity check matrix).
In the documentation https://pymatching.readthedocs.io/en/stable/toric-code-example.html#Simulating-circuit-level-noise , you propose to test surface code with circuit noise.
Do you know if it is possible to extract the corresponding parity check matrix from the stim circuit or from the pymatching decoder instantiated with the stim circuit?
Thanks!

**Comment by oscarhiggott** [comment]
Hi @yoyocni, apologies for the slow response. You can use the [detector_error_model_to_check_matrices](https://github.com/oscarhiggott/BeliefMatching/blob/2ff4f1dfe703c6efc146f268cafea24adb6474e1/src/beliefmatching/belief_matching.py#L61) method from the [BeliefMatching](https://pypi.org/project/beliefmatching/) python package. Is that the check matrix you were looking for?

**Comment by Lucas-Wye** [comment]
```python
import stim
import pymatching
import numpy as np


def count_logical_errors(circuit: stim.Circuit, num_shots: int) -> int:
    # Sample the circuit.
    sampler = circuit.compile_detector_sampler()
    detection_events, observable_flips = sampler.sample(
        num_shots, separate_observables=True)

    # Configure a decoder using the circuit.
    detector_error_model = circuit.detector_error_model(decompose_errors=True)
    print(detector_error_model)

    from beliefmatching import detector_error_model_to_check_matrices
    '''
        check_matrix: csc_matrix
        observables_matrix: csc_matrix
        edge_check_matrix: csc_matrix
        edge_observables_matrix: csc_matrix
        hyperedge_to_edge_matrix: csc_matrix
        priors: np.ndarray
    '''
    dem_matrix = detector_error_model_to_check_matrices(detector_error_model)
    print(f"\nparity-check matrix: {dem_matrix.check_matrix}\n\n")

    matcher = pymatching.Matching.from_detector_error_model(
        detector_error_model)

    # Run the decoder.
    predictions = matcher.decode_batch(detection_events)

    # Count the mistakes.
    num_errors = 0
    for shot in range(num_shots):
        actual_for_shot = observable_flips[shot]
        predicted_for_shot = predictions[shot]
        if not np.array_equal(actual_for_shot, predicted_for_shot):
            num_errors += 1
    print(f"number of errors: {num_errors}")

    # use csc_matrix
    _check_matrix = dem_matrix.check_matrix
    weights = dem_matrix.priors
    matcher = pymatching.Matching.from_check_matrix(_check_matrix,
                                                    weights=weights)

    # Count the mistakes.
    _num_errors = 0
    for shot in range(num_shots):
        actual_for_shot = observable_flips[shot]
        predicted_for_shot = predictions[shot]
        if not np.array_equal(actual_for_shot, predicted_for_shot):
            _num_errors += 1
    print(f"number of errors: {_num_errors}")

    return num_errors


if __name__ == "__main__":
    circuit = stim.Circuit.generated("surface_code:rotated_memory_x",
                                 distance=5,
                                 rounds=5,
                                 after_clifford_depolarization=0.005)
    num_errs = count_logical_errors(circuit, 30)

```

I use your method @oscarhiggott to convert dem to parity-check matrix, but there is an error:

```log
Traceback (most recent call last):
  File "/home/qlc/algo/decoder/examples/ex_circuit2matrix.py", line 71, in <module>
    num_errs = count_logical_errors(circuit, 30)
  File "/home/qlc/algo/decoder/examples/ex_circuit2matrix.py", line 46, in count_logical_errors
    matcher = pymatching.Matching.from_check_matrix(_check_matrix,
  File "/home/qlc/algo/.venv/lib/python3.10/site-packages/pymatching/matching.py", line 1040, in from_check_matrix
    m.load_from_check_matrix(
  File "/home/qlc/algo/.venv/lib/python3.10/site-packages/pymatching/matching.py", line 1232, in load_from_check_matrix
    self._matching_graph = _cpp_pm.sparse_column_check_matrix_to_matching_graph(check_matrix, weights,
ValueError: `check_matrix` must contain at most two ones per column, but column 4 has 3 ones.
```

**Comment by oscarhiggott** [comment]
What's the reason you want to load from check matrix rather than just directly from the dem?

If you want to load the `pymatching.Matching` from the check matrices here you'll want to use the `edge_check_matrix` and `edge_observables_matrix` instead, which are guaranteed to have columns of weight at most two (e.g. each column corresponds to an edge error).

For an example, see [these lines](https://github.com/oscarhiggott/BeliefMatching/blob/4458c278bbec273c8c1a26411dadccc49222f8ef/src/beliefmatching/belief_matching.py#L352-L358) in the belief-matching repo.

**Comment by Lucas-Wye** [comment]
> What's the reason you want to load from check matrix rather than just directly from the dem?
> 
> If you want to load the `pymatching.Matching` from the check matrices here you'll want to use the `edge_check_matrix` and `edge_observables_matrix` instead, which are guaranteed to have columns of weight at most two (e.g. each column corresponds to an edge error).
> 
> For an example, see [these lines](https://github.com/oscarhiggott/BeliefMatching/blob/4458c278bbec273c8c1a26411dadccc49222f8ef/src/beliefmatching/belief_matching.py#L352-L358) in the belief-matching repo.

Thanks a lot! Because I am trying to test the output parity-check matrix. I already read your code but I am confused about the `weights`.

```Python
        matching = pymatching.Matching.from_check_matrix(
            self._matrices.edge_check_matrix,
            weights=-np.log(ps_e),
            faults_matrix=self._matrices.edge_observables_matrix,
            use_virtual_boundary_node=True,
        )
        return matching.decode(syndrome)
```

The parity-check matrix is obtained from the function `detector_error_model_to_check_matrices`, but weights are not generated during this function?

In my implementation, I use the DemMatrices.priors as the `weights`. But In your code, it is much more complex to obtain the weights, where:
```
            weights=-np.log(ps_e),
```

**Comment by oscarhiggott** [comment]
Yes [this code](https://github.com/oscarhiggott/BeliefMatching/blob/4458c278bbec273c8c1a26411dadccc49222f8ef/src/beliefmatching/belief_matching.py#L348-L351) calculates the weights (approximately).

E.g. you can do:

```
edge_probs = dem_matrix.hyperedge_to_edge_matrix @ dem_matrix.priors
eps = 1e-14
edge_probs[edge_probs > 1 - eps] = 1 - eps
edge_probs[edge_probs < eps] = eps
edge_weights = np.log((1 - edge_probs) / edge_probs)
```

This is a bit approximate, as really you should combine two probabilities `p1` and `p2` using `p1 * (1 - p2) + p2 * (1 - p1)` rather than simply adding them `p1 + p2` as I do here.

Also, the code above adds the probability of a hyperedge to the probability of an edge, if that edge is in the decomposition of the hyperedge. Alternatively, you could only assign a probability to an edge corresponding to exactly the probability of that error in the dem (with no extra contributions from the DEM). This corresponds to finding the subset of `dem_matrix.priors` corresponding to the edge-like errors. E.g. you can map to this by zeroing out all columns in `dem_matrix.hyperedge_to_edge_matrix` that have more than one nonzero element.

**Comment by Lucas-Wye** [comment]
> Yes [this code](https://github.com/oscarhiggott/BeliefMatching/blob/4458c278bbec273c8c1a26411dadccc49222f8ef/src/beliefmatching/belief_matching.py#L348-L351) calculates the weights (approximately).
> 
> E.g. you can do:
> 
> ```
> edge_probs = dem_matrix.hyperedge_to_edge_matrix @ dem_matrix.priors
> eps = 1e-14
> edge_probs[edge_probs > 1 - eps] = 1 - eps
> edge_probs[edge_probs < eps] = eps
> edge_weights = np.log((1 - edge_probs) / edge_probs)
> ```
> 
> This is a bit approximate, as really you should combine two probabilities `p1` and `p2` using `p1 * (1 - p2) + p2 * (1 - p1)` rather than simply adding them `p1 + p2` as I do here.
> 
> Also, the code above adds the probability of a hyperedge to the probability of an edge, if that edge is in the decomposition of the hyperedge. Alternatively, you could only assign a probability to an edge corresponding to exactly the probability of that error in the dem (with no extra contributions from the DEM). This corresponds to finding the subset of `dem_matrix.priors` corresponding to the edge-like errors. E.g. you can map to this by zeroing out all columns in `dem_matrix.hyperedge_to_edge_matrix` that have more than one nonzero element.

It works. Thank you so mcuh!
